# For more info on HTTP files go to https://aka.ms/vs/httpfile

@Teste_HostAddress = https://localhoast:7284

GET {{Teste_HostAddress}}/api/ModeloTestes
Content-Type: application/json
{
  //Tranquilo
}
###

POST {{Teste_HostAddress}}/api/ModeloTeste
Content-Type: application/json
{
  "Name": "Tranquilo?",
  "Complete": true
}
###
